### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by MaxPeal** [intra2net/guibot#11]
"Currently only Python 2.7 is supported."
form https://github.com/intra2net/guibot/wiki/Packaging

but Python 2.7 is EOL, Support officially stopped January 1 2020,

**Comment by pevogam** [comment]
Hi @MaxPeal, in fact we now only support Python 3 and no longer Python 2. I guess you got an outdated part of the documentation, thanks for spotting this! Will take care to fix this today.

**Comment by pevogam** [comment]
Alright, updated accordingly.
