### ISSUE TITLE
Issue Using Tesseract

### ISSUE THREAD

**Issue by tallsmallone** [intra2net/guibot#27]
I am trying to run the Text Detection and I am getting this error:

> File "E:\Projects\fhm-test-automation\.venv\lib\site-packages\guibot\region.py", line 406, in find
    found_pics = cv_backend.find(target, screen_capture)
  File "E:\Projects\fhm-test-automation\.venv\lib\site-packages\guibot\finder.py", line 2169, in find
    output = self.ocr.image_to_string(text_img,
  File "E:\Projects\fhm-test-automation\.venv\lib\site-packages\pytesseract\pytesseract.py", line 409, in image_to_string
    return {
  File "E:\Projects\fhm-test-automation\.venv\lib\site-packages\pytesseract\pytesseract.py", line 412, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "E:\Projects\fhm-test-automation\.venv\lib\site-packages\pytesseract\pytesseract.py", line 287, in run_and_get_output
    run_tesseract(**kwargs)
  File "E:\Projects\fhm-test-automation\.venv\lib\site-packages\pytesseract\pytesseract.py", line 263, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file ../misctessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

I have set the Environmental Variable TESSDATA_PREFIX to the proper location and I have tested pytesseract separately and it works.

It is entirely possible I missed a GlobalConfig item but I cannot seem to figure this out.

I am running this in windows 10 (the program I am automating is only windows).

The lines in questions are:
> from guibot.finder import TextFinder
from guibot.region import Region
from guibot.target import Text

>self.__text_finder = Region(cv=TextFinder())
self.__text_finder.click(Text(str(2026)))

**Comment by pevogam** [comment]
Exactly, there is a config item since some people store multiple copies of Tesseract language data. This is an excerpt from the https://github.com/intra2net/guibot/blob/master/docs/examples/fixed_image_sampler.py file:
```python
#finder.params["feature"]["ransacReprojThreshold"].value = 25.0
#finder.params["fdetect"]["MaxFeatures"].value = 10
#finder.params["text"]["datapath"].value = "../../misc"
```
It is an example of switching among various backends and using parameters particular to them. All parameters you have at your disposal can be seen if in the `text` section but you can use the `datapath` to point to the data you would like to use for Guibot's OCR backends.

**Comment by pevogam** [comment]
I suspect part of your issue here is in the fact that you could have installed the wheel package and didn't have the `misc` data included by default. It is included in all RPM-s and Debian packages we produce but we chose to keep the wheel package rather minimal. However, as the `misc` folder and the data inside of it is ~119M I am starting to think it is not too much to include in the wheel.

**Comment by linkyeu** [comment]
Does it mean that I need to point `finder.params["text"]["datapath"].value` to a directory which contains `eng.traineddata` file?

**Comment by pevogam** [comment]
> Does it mean that I need to point `finder.params["text"]["datapath"].value` to a directory which contains `eng.traineddata` file?

Almost but not exactly - rather the directory containing the `tessdata` directory. In the above case the `misc` directory with provide if the repo is cloned is the one containing custom `tessdata` but you can direct to any `tessdata` containing directory.

**Comment by treylav** [comment]
I have a similar problem with standalone Tesseract configured and working correctly too. Can I set the path to the ``tessdata`` folder via ``guibot.config.GlobalConfig``? For example, backend is set with the following lines:
```python
guibot.config.GlobalConfig.display_control_backend = "pyautogui"
guibot.config.GlobalConfig.text_ocr_backend = "pytesseract"
```
But I don't fully understand through which object I should modify the path to ``tessdata``.

**Comment by pevogam** [comment]
The global config only changes the defaults (including default backends) for any `finder` you initialize and this includes mostly the choice of backend and some screen control options that are general for all backends. If you want to set the backend specific settings you have to configure the backend itself, see e.g. the section "MATCH CONFIGURATION STRUCTURE" in https://github.com/intra2net/guibot/wiki/Match-Settings-Tutorial or alternatively the example in https://github.com/intra2net/guibot/blob/master/docs/examples/fixed_image_sampler.py.

**Comment by pevogam** [comment]
This should work now and take into account the environment variable if no custom tessdata is present:
```
$ export TESSDATA_PREFIX=/usr/share/tesseract/tessdata/
$ python3
Python 3.8.8 (default, Nov  9 2021, 13:31:34) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from guibot.finder import TextFinder
>>> from guibot.region import Region
>>> from guibot.target import Text
>>> f = Region(cv=TextFinder())
>>> import os
>>> os.path.exists(f.cv_backend.params["text"]["datapath"].value)
False
>>> f.exists(Text("a"))
>>>
```
Thanks for your patience an hopefully OCR is easier to use now.
