### ISSUE TITLE
Add support for pyautogui

### ISSUE THREAD

**Issue by link89** [intra2net/guibot#5]
Hi, do you have a plan to add `pyautogui` as a DC backend? It provides more operation than `autopy` does.

**Comment by pevogam** [comment]
Hi there! This is a good idea so we will definitely look into it. If you really need the backend it should hopefully be easy enough to define a new DC class with some minimal functionality for your own use cases that we could than later extend on as well.

**Comment by pevogam** [comment]
I have created a PR #21 addressing this that will be in draft state over the weekend but should be complete by the end of the following week.

**Comment by pevogam** [comment]
Hi @link89, the PyAutoGUI backend is now available, let me know if you have any feedback from using it later on.
