### ISSUE TITLE
Feature request: add support for PIKVM as a backend:

### ISSUE THREAD

**Issue by DIGist** [intra2net/guibot#51]
Feature request: add support for PIKVM as a backend:
https://docs.pikvm.org/api/

**Comment by pevogam** [comment]
Hi @DIGist, we already support VNC and I read from the docs of this project that they do provide VNC server in their product. So I would recommend to either:

1) Use VNCDoTool as a backend to connect to that VNC server.
2) Provide such API calls via a standalone backend in a standalone repository as this one has already grown a bit too much even with the current mainstream backends and thus already endures higher maintenance costs.
