### ISSUE TITLE
Imrove accessibility and coverage of the documentation

### ISSUE THREAD

**Issue by marcovisibelli** [intra2net/guibot#6]
The documentation for the project is not easy to find and often not complete.

**Comment by pevogam** [comment]
There is one at https://guibot.readthedocs.io/en/latest/ as pointed out in the README file. If you mean API documentation, you have to click on the side-panel from the link above saying "guibot package" as is typically done with RTD web pages and sphinx documentation in particular.

**Comment by pevogam** [comment]
This is hopefully somewhat remedied in #19. Feel free to open a more specific issue about particular documentation that you had trouble with otherwise.
